### ISSUE TITLE
为什么我运行不了，真的可以抢票吗？我将周杰伦的换成薛之谦的可以吗？支不支持移动端

### ISSUE THREAD

**Issue by cheng070205** [haihaimx/damaiqiangpiao#1]

**Comment by haihaimx** [comment]
可以换的 要适当修改一下

**Comment by haihaimx** [comment]
周杰伦只是我弄都时候懒得改名字了

**Comment by chengchenglovejiayi** [comment]
我是只需要换这个就可以吗，target_url = 'https://m.damai.cn/damai/detail/item.html?utm=&itemId=710601748792&from=appshare'，不过这个网站是移动端的，可以抢到票吗？恳求大哥帮帮忙。

**Comment by cheng070205** [comment]
我是只需要换这个就可以吗，target_url = 'https://m.damai.cn/damai/detail/item.html?itemId=703388284765&spm=a2o71.category.itemlist.ditem_0&sqm=dianying.h5.unknown.value'，不过这个网站是移动端的，可以抢到票吗？恳求大哥帮帮忙。]

**Comment by PlutoEr-001** [comment]
最后订单提交会有滑块的人机验证，过不去

**Comment by PlutoEr-001** [comment]
这个应该是一个比较早版本的大麦网页的抢票，现在他的页面布局变了

**Comment by dadasds** [comment]
可以加个联系方式  教我一下吗  18016588696  有偿

**Comment by 1181691792** [comment]
网页购票都已经不行了，怎么还有人用

**Comment by 1181691792** [comment]
热门的演唱会网页购票都已经不行了，怎么还有人用

**Comment by dadasds** [comment]
所以有大佬开发一下移动端抢的吗

**Comment by PlutoEr-001** [comment]
我也不会过人机验证，放弃用脚本抢了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haihaimx/damaiqiangpiao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haihaimx/damaiqiangpiao] 为什么我运行不了，真的可以抢票吗？我将周杰伦的换成薛之谦的可以吗？支不支持移动端 (Issue #1)





 
可以加个联系方式  教我一下吗  18016588696  有偿

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
